### ISSUE TITLE
Basic display api no longer working

### ISSUE THREAD

**Issue by pratikbaid3** [AyeshaIftikhar/insta_login#11]
```On September 4, 2024, we announced the deprecation of the Instagram Basic Display API.

Starting December 4, 2024, all requests to the Instagram Basic Display API will return an error message. We recommend that you migrate your app to the [Instagram API](https://developers.facebook.com/docs/instagram-platform) to avoid any disruption to your services.
```

Since facebook as depricated the basic details api, the sdk is no longer working. Can you provide some solution for this?

**Comment by AyeshaIftikhar** [comment]
I will look into this.

**Comment by pratikbaid3** [comment]
@AyeshaIftikhar is this issue fixed? Saw it closed.

**Comment by AyeshaIftikhar** [comment]
No, it is not fixed. As the facebook discontinued the Instagram Basic
Display Api and the new api requires business verification and alot of
other things as per my understanding.

Thanks and Regards,
Ayesha Iftikhar
+923137128036
https://ayesha-iftikhar.web.app
