### ISSUE TITLE
OAuthException

### ISSUE THREAD

**Issue by faisal-kabir** [AyeshaIftikhar/insta_login#2]
A few days ago it was working, but suddenly it stopped working. I know why.

> flutter: WebView is loading (progress : 10%)
flutter: url change to https://api.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
flutter: url: https://api.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
flutter: authorization code: https://api.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=Somethingr&scope=user_profile,user_media&response_type=code
flutter: allowing navigation to https://api.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
[log] PlatformException
[log] PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 1, WKJavaScriptExceptionMessage: ReferenceError: Can't find variable: InstaLogin, WKJavaScriptExceptionSourceURL: Unsupported Type: undefined, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 11}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1110:7)
asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:407:7)
asynchronous suspension>
flutter: Page started loading: https://api.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
flutter: allowing navigation to https://www.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
flutter: url change to https://www.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
flutter: url: https://www.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
flutter: authorization code: https://www.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code
flutter: WebView is loading (progress : 100%)
flutter: response: {"error_type": "OAuthException", "code": 400, "error_message": "Invalid platform app"}
flutter: isDone: {error_type: OAuthException, code: 400, error_message: Invalid platform app}
flutter: response: {"error_type": "OAuthException", "code": 400, "error_message": "Invalid platform app"}
flutter: isDone: {error_type: OAuthException, code: 400, error_message: Invalid platform app}
flutter: WebView is loading (progress : 10%)
flutter: WebView is loading (progress : 12%)
flutter: WebView is loading (progress : 47%)
flutter: WebView is loading (progress : 100%)
flutter: Page finished loading: https://www.instagram.com/oauth/authorize?client_id=1230657137894952&redirect_uri=something&scope=user_profile,user_media&response_type=code

**Comment by AyeshaIftikhar** [comment]
Can you please share the minimum reproducible code?

**Comment by AyeshaIftikhar** [comment]
Did you add an ios application in the facebook developer platform?

Thanks and Regards,
Ayesha Iftikhar
+923137128036
https://ayesha-iftikhar.web.app

**Comment by faisal-kabir** [comment]
Yes, I did it.

**Comment by AyeshaIftikhar** [comment]
I am unable to reproduce your issues. Is your facebook platform application is live and ios app is also on the appstore
