### ISSUE TITLE
Help my with flutterflow

### ISSUE THREAD

**Issue by ANDREAX22** [AyeshaIftikhar/insta_login#3]
I'm trying to implement Instagram authentication on FlutterFlow, so I created a custom widget. However, I'm encountering this error: 'Because test1234 depends on insta_login any which requires SDK version >=3.2.0 <4.0.0, version solving failed.' I don't understand it very well, but I can only import components from pub.dev, and I can't modify the pubspec.yaml. Could you help me resolve this? The code for the custom widget is as follows:

"// Automatic FlutterFlow imports
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

// Set your widget name, define your parameter, and then add the
// boilerplate code using the green button on the right!
import 'package:insta_login/insta_login.dart'; // Assicurati di importare il tuo pacchetto Instagram

class InstagramConnectWidget extends StatefulWidget {
  const InstagramConnectWidget({Key? key}) : super(key: key);

  @override
  _InstagramConnectWidgetState createState() => _InstagramConnectWidgetState();
}

class _InstagramConnectWidgetState extends State<InstagramConnectWidget> {
  String token = '';
  String userid = '';
  String username = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Instagram Connection')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 20),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (token.isNotEmpty || userid.isNotEmpty || username.isNotEmpty)
                Text(
                  'Access Token: $token\n\nUser Id: $userid\n\nUsername: $username',
                )
              else
                SizedBox(
                  width: double
                      .infinity, // Aggiunto per risolvere l'errore "Width not specified"
                  height: 50,
                  child: ElevatedButton(
                    onPressed: () {
                      Navigator.of(context).push(
                        MaterialPageRoute(
                          builder: (context) {
                            return InstaView(
                              instaAppId: '215643524910532',
                              instaAppSecret:
                                  'b19d87bf98b632e0319f2ebab495b345',
                              redirectUrl: 'https://ayesha-iftikhar.web.app/',
                              onComplete: (_token, _userid, _username) {
                                WidgetsBinding.instance?.addPostFrameCallback(
                                  (timeStamp) {
                                    setState(() {
                                      token = _token;
                                      userid = _userid;
                                      username = _username;
                                    });
                                  },
                                );
                              },
                            );
                          },
                        ),
                      );
                    },
                    child: Text('Connect to Instagram'),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
"

**Comment by AyeshaIftikhar** [comment]
**'Because test1234 depends on insta_login any which requires SDK version >=3.2.0 <4.0.0, version solving failed.' I don't understand it very well, but I can only import components from pub.dev, and I can't modify the pubspec.yaml.** 

The minimum flutter version for insta_login is 
```
environment:
  sdk: '>=3.2.0 <4.0.0'
```
You need to upgrade your project.

**Comment by AyeshaIftikhar** [comment]
As I didn't get anymore information from you. I am assuming the issue has been fixed. I am closing this issue. You can always reopen it.
