### ISSUE TITLE
i get issue when insta login button clicked

### ISSUE THREAD

**Issue by harshghelani18** [AyeshaIftikhar/insta_login#9]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: FormatException: Unexpected character (at character 1)
E/flutter (10160): Sorry, this content isn't available right now
 and in webview it displays please wait for few minutes

**Comment by AyeshaIftikhar** [comment]
Can you provide the minimum reproducable code?
